### ISSUE TITLE
java.lang.RuntimeException: Unable to start service changjoopark.com.flutter_foreground_plugin.FlutterForegroundService@34e8f12 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference

### ISSUE THREAD

**Issue by xxzj990** [ChangJoo-Park/flutter_foreground_service_plugin#18]
Got this error after running for a while

Detail ==============>

11-20 18:45:22.035 28779-28779/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx, PID: 28779
    java.lang.RuntimeException: Unable to start service changjoopark.com.flutter_foreground_plugin.FlutterForegroundService@34e8f12 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3057)
        at android.app.ActivityThread.access$2200(ActivityThread.java:165)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5546)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
        at changjoopark.com.flutter_foreground_plugin.FlutterForegroundService.onStartCommand(FlutterForegroundService.java:26)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3040)
        at android.app.ActivityThread.access$2200(ActivityThread.java:165) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5546) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by cdfq152313** [comment]
Do you know how to reproduce this issue?
I found the same issue by crash report. But I cannot reproduce it.

**Comment by xxzj990** [comment]
@cdfq152313 This problem must appear in my project.I do not know why.

I made the following changes to the library code,problem no longer occurs:

```java
    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        if (intent == null || intent.getAction() == null) {
            return START_REDELIVER_INTENT;
        }
        ...
    }
```

**Comment by cdfq152313** [comment]
https://github.com/ChangJoo-Park/flutter_foreground_service_plugin/pull/20

@xxzj990 

I make a pull request for this issue.

I return START_NOT_STICKY instead of START_REDELIVER_INTENT(or START_STICKY ). Android will try to launch foreground service again when your app crash unexpectedly. In this case, flutter engine will not be launched as well. So there is no need to restart foreground service again.

I hope I didn't get it wrong.

**Comment by xxzj990** [comment]
> #20
> 
> @xxzj990
> 
> I make a pull request for this issue.
> 
> I return START_NOT_STICKY instead of START_REDELIVER_INTENT(or START_STICKY ). Android will try to launch foreground service again when your app crash unexpectedly. In this case, flutter engine will not be launched as well. So there is no need to restart foreground service again.
> 
> I hope I didn't get it wrong.

Thank you!I will try.
